Section "InputClass"
	Identifier "touchpad"
	Driver "synaptics"
	MatchIsTouchpad "on"
	#MatchDevicePath "/dev/input/event6"
 
	Option		"TapButton1"								"1"
	Option		"TapButton2"								"3"
	Option		"TapButton3"								"2"
	Option		"VertTwoFingerScroll"		    "true"
	Option		"HorizTwoFingerScroll"			"false"
	Option		"VertScrollDelta"				    "-111"
	Option		"HorizScrollDelta"			    "-111"
	Option		"CoastingSpeed"					    "15"
	Option		"CoastingFriction"			    "15"
#	Option		"HorizHysteresis"				    "0"
#	Option		"VertHysteresis"				    "0"
#	Option		"MinSpeed"									"1.0"		
#	Option		"MaxSpeed"									"1.75"
#	Option		"AccelFactor"								"0.0434688"
#	Option 		"PalmDetect" 								"1"
#	Option 		"PalmMinWidth" 					    "10"
#	Option 		"PalmMinZ" 									"200"
#	Option 		"SyndaemonDisable" 			    "1"
EndSection
